### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Kreijstal** [chardoncs/kurumi#1]
According to poppler-rs all crates using it should be GPL licensed, but your crate is MIT license

**Comment by chardoncs** [comment]
Sorry, I believe you have confused [poppler-rs](https://crates.io/crates/poppler-rs) by GNOME with [poppler-rs](https://crates.io/crates/poppler) by DMS.rs.

**Comment by Kreijstal** [comment]
https://poppler.freedesktop.org/ use xpdf.. which is GPL

**Comment by chardoncs** [comment]
![screenshot](https://github.com/user-attachments/assets/f22f0a99-e69a-4e35-99d4-64dfb9637728)

**Comment by chardoncs** [comment]
Also, about XPDF, you have to know what you're talking about:

![licenses](https://github.com/user-attachments/assets/ba7feeba-bd4e-43fd-adb4-d20afe27a70c)

**Comment by alerque** [comment]
@chardoncs All that chart and screenshot does is prove the Gnome poppler-rs crate is breaking the license.
